### PR TITLE
Sherif awofiranye

### PR DESCRIPTION
**Pull request by iAmSherifCodes**
Sherif awofiranye

### CODE REVIEW

**Comment by iAmSherifCodes** [comment]
Sherif Awofiranye(Week 2)

**Comment by codewithmide** [comment]
Hi, @iAmSherifCodes could you please put your code into a single folder with your name? This will enable us to have a clean repository and avoid conflicts with other submissions. :) Thank you!

**Comment by iAmSherifCodes** [comment]
> Hi, @iAmSherifCodes could you please put your code into a single folder with your name? This will enable us to have a clean repository and avoid conflicts with other submissions. :) Thank you!

It is now done, is it okay now?

**Comment by codewithmide** [comment]
Hi @iAmSherif-iCode Please push just your code alone. It seems you cloned others submission

**Pull request closed without merging**
