### PR TITLE
Arrays-and-String

### PR DESCRIPTION
**Pull request by Peter-TMK**
Working solution of exercise-1 of the array-string assessment

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi, @Peter-TMK could you please put your code into a single folder with your name? This will enable us to have a clean repository and avoid conflicts with other submissions. :) Thank you!

**Comment by Peter-TMK** [comment]
Ok, I'll do that

**Comment by Peter-TMK** [comment]
Can I get exactly what you mean?
I should name the folder with my name right?
Because my code files already are in one folder.
Please let me know if that's what you mean.

**Comment by codewithmide** [comment]
Exactly.

**Comment by Peter-TMK** [comment]
I just changed the folder name to my name directly using GitHub. Please can you help to confirm that I made the recommended edit? Thanks

**Comment by codewithmide** [comment]
Both your class.js and test.js should be in a sub-folder/sub-directory named after you.

Kindly submit a new PR. We don't want to make the code review tedious for the tutors.

**Comment by Peter-TMK** [comment]
Ok, the root folder's name should be as it is from the fork, right
?

**Comment by codewithmide** [comment]
Yes please

**Pull request merged**
