### PR TITLE
Submission for exercises 1 and 2

### PR DESCRIPTION
**Pull request by dev-juri**
Oluwafemi's Submission for Exercise 1 and 2:
1. Dynamic Array with methods to get and set a value at an index, add a value to the array and methods to return the size and capacity of the array.
2. Implementation of the Linear search algorithm.

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi, @dev-juri could you please put your code into a single folder with your name? This will enable us to have a clean repository and avoid conflicts with other submissions. :) Thank you!

**Comment by dev-juri** [comment]
Hi @codewithmide, I have reformatted the code. Kindly check again.

**Comment by dev-juri** [comment]
Hi @codewithmide, I have reformatted the code. Kindly check again.

**Comment by codewithmide** [comment]
LGTM 👏

**Pull request merged**
