### PR TITLE
My array assigbment

### PR DESCRIPTION
**Pull request by UshieChris**

### CODE REVIEW

**Comment by UshieChris** [comment]
Nice Assignment

**Comment by codewithmide** [comment]
Hi, @UshieChris could you please put your code into a single folder with your name? This will enable us to have a clean repository and avoid conflicts with other submissions. :) Thank you!

**Comment by UshieChris** [comment]
My work is inside a single folder, and it was without a conflict when I
raised a PR. Do you mean I should add my name inside the folder?

**Comment by codewithmide** [comment]
You pushed a single file. Create a folder named after you,put your file inside and push again.

Your folder must bear your name remember.

**Comment by UshieChris** [comment]
Okay, thanks

**Pull request merged**
